version: '2'
services:
  Vuln-Machine:
    image: 'simone02/vuln-gallery-ctf:v1'
    stdin_open: true
    tty: true
    networks:
      network:
        ipv4_address: 172.20.0.10
networks:
  network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
